In [1]:
from utils import *

In [2]:
x, y, x_train, x_test, y_train, y_test, variables = preparer_donnees('credit_scoring.csv')

print("Variables utilisées pour l'entrainement :", variables)
print("Dimensions de x_train:", x_train.shape)
print("Dimensions de y_train:", y_train.shape)
print("Dimensions de x_test:", x_test.shape)
print("Dimensions de y_test:", y_test.shape)

Répartition des données : 72.21% positives, 27.79% négatives
Données prêtes pour l'entrainement...
Variables utilisées pour l'entrainement : ['Seniority' 'Home' 'Time' 'Age' 'Marital' 'Records' 'Job' 'Expenses'
 'Income' 'Assets' 'Debt' 'Amount' 'Price']
Dimensions de x_train: (2187, 13)
Dimensions de y_train: (2187,)
Dimensions de x_test: (2188, 13)
Dimensions de y_test: (2188,)


## Comparaison train test

In [3]:
X_train, X_test, Y_train, Y_test = decoupage_train_test(x, y, 0.33)
scaler = StandardScaler()
x_norm = scaler.fit_transform(x)
apprentissage_train_test(X_train, X_test, Y_train, Y_test, clfs)

MLP -> Test Score: 73.36%
[[  37  364]
 [  25 1018]]

DT -> Test Score: 77.33%
[[212 189]
 [201 842]]

KNN -> Test Score: 73.76%
[[125 276]
 [143 900]]

CART -> Test Score: 79.45%
[[218 183]
 [162 881]]

ID3 -> Test Score: 80.06%
[[229 172]
 [167 876]]

Bagging -> Test Score: 77.97%
[[129 272]
 [ 53 990]]

AdaBoost -> Test Score: 79.34%
[[217 184]
 [163 880]]

RandomForest -> Test Score: 75.40%
[[  65  336]
 [  18 1025]]



In [4]:
X_train_norm, X_test_norm = normalisation(x_train, x_test)
apprentissage_train_test(X_train_norm, X_test_norm, y_train, y_test, clfs)

MLP -> Test Score: 79.60%
[[ 348  256]
 [ 278 1306]]

DT -> Test Score: 77.27%
[[ 322  282]
 [ 315 1269]]

KNN -> Test Score: 78.17%
[[ 286  318]
 [ 223 1361]]

CART -> Test Score: 76.73%
[[ 167  437]
 [  87 1497]]

ID3 -> Test Score: 76.58%
[[ 167  437]
 [  92 1492]]

Bagging -> Test Score: 78.13%
[[ 200  404]
 [  88 1496]]

AdaBoost -> Test Score: 77.81%
[[ 299  305]
 [ 257 1327]]

RandomForest -> Test Score: 75.84%
[[  98  506]
 [  17 1567]]



## Comparaison CV

In [ ]:
'''def apprentissage_CV(X, Y, clfs):
    """
    Évalue plusieurs classifieurs avec validation croisée 10-fold
    Retourne le meilleur classifieur et son score
    
    Args:
        X: Features
        Y: Target
        clfs: Dictionnaire de classifieurs
        
    Returns:
        tuple: (nom_meilleur_classifieur, meilleur_score_moyen)
    """
    kf = KFold(n_splits=10, shuffle=True, random_state=0)
    
    best_score = 0
    best_clf_name = ""
    
    for i in clfs:
        clf = clfs[i]
        
        cv_scores = cross_val_score(
            clf, X, Y, 
            cv = kf, 
            scoring = monscore,  
            n_jobs = 1
        )
        
        mean_score = np.mean(cv_scores)
        std_score = np.std(cv_scores) 
        
        print("Score de {0} est: {1:.3f}% ± {2:.3f}%".format(i, mean_score*100, std_score*100))
        
        if mean_score > best_score:
            best_score = mean_score
            best_clf_name = i
    
    return best_clf_name, best_score'''


In [6]:
def comparaison_CV(X, Y, clfs):
    """
    Compare plusieurs classifieurs et retourne le meilleur
    
    Args:
        X: Features
        Y: Target
        clfs: Dictionnaire de classifieurs
        
    Returns:
        str: Nom du meilleur classifieur
    """
    
    kf = KFold(n_splits=10, shuffle=True, random_state=0)
    best_score = 0
    best_clf_name = ""
    
    scores_dict = {}
    
    for clf_name in clfs:
        clf = clfs[clf_name]
        
        cv_scores = cross_val_score(
            clf, X, Y, 
            cv=kf, 
            scoring=monscore,
            n_jobs=1  # Changé à 1 pour éviter les problèmes
        )
        
        mean_score = np.mean(cv_scores)
        std_score = np.std(cv_scores)
        
        scores_dict[clf_name] = mean_score
        
        print(f"{clf_name:15s}: {mean_score:.3f} ± {std_score:.3f}")
        
        if mean_score > best_score:
            best_score = mean_score
            best_clf_name = clf_name
    
    print(f"\nMeilleur classifieur: {best_clf_name} avec score: {best_score:.3f}")
    
    return best_clf_name


In [7]:
print("\n" + "="*60)
print("VALIDATION CROISÉE - DONNÉES ORIGINALES (TOUTES LES DONNÉES)")
print("="*60)
best_classifieur, best_score = apprentissage_CV(x, y, clfs)

print("\n" + "="*60)
print("VALIDATION CROISÉE - DONNÉES NORMALISÉES (TOUTES LES DONNÉES)")
print("="*60)
best_classifieur_norm, best_score_norm = apprentissage_CV(x_norm, y, clfs)




VALIDATION CROISÉE - DONNÉES ORIGINALES (TOUTES LES DONNÉES)
Score de MLP est: 75.850% ± 1.587%
Score de DT est: 76.732% ± 2.155%
Score de KNN est: 74.108% ± 1.709%
Score de CART est: 77.819% ± 1.528%
Score de ID3 est: 76.862% ± 2.475%
Score de Bagging est: 78.252% ± 1.784%
Score de AdaBoost est: 78.105% ± 1.841%
Score de RandomForest est: 75.560% ± 2.616%

VALIDATION CROISÉE - DONNÉES NORMALISÉES (TOUTES LES DONNÉES)
Score de MLP est: 80.878% ± 1.780%
Score de DT est: 76.747% ± 2.155%
Score de KNN est: 78.929% ± 1.689%
Score de CART est: 77.819% ± 1.528%
Score de ID3 est: 76.862% ± 2.475%
Score de Bagging est: 78.252% ± 1.784%
Score de AdaBoost est: 78.127% ± 1.835%
Score de RandomForest est: 75.560% ± 2.616%


In [8]:
print("\n" + "="*60)
print("COMPARAISON CV - DONNÉES ORIGINALES")
print("="*60)
meilleur_original = comparaison_CV(x, y, clfs)

print("\n" + "="*60)
print("COMPARAISON CV - DONNÉES NORMALISÉES")
print("="*60)
meilleur_norm = comparaison_CV(x_norm, y, clfs)


COMPARAISON CV - DONNÉES ORIGINALES
MLP            : 0.758 ± 0.016
DT             : 0.767 ± 0.022
KNN            : 0.741 ± 0.017
CART           : 0.778 ± 0.015
ID3            : 0.769 ± 0.025
Bagging        : 0.783 ± 0.018
AdaBoost       : 0.781 ± 0.018
RandomForest   : 0.756 ± 0.026

Meilleur classifieur: Bagging avec score: 0.783

COMPARAISON CV - DONNÉES NORMALISÉES
MLP            : 0.809 ± 0.018
DT             : 0.767 ± 0.022
KNN            : 0.789 ± 0.017
CART           : 0.778 ± 0.015
ID3            : 0.769 ± 0.025
Bagging        : 0.783 ± 0.018
AdaBoost       : 0.781 ± 0.018
RandomForest   : 0.756 ± 0.026

Meilleur classifieur: MLP avec score: 0.809


In [9]:
print("\n" + "="*60)
print("SYNTHÈSE DES RÉSULTATS")
print("="*60)
print(f"Meilleur sur données originales: {best_classifieur}")
print(f"Score: {best_score:.3f}")

print(f"\nMeilleur sur données normalisées: {best_classifieur_norm}")
print(f"Score: {best_score_norm:.3f}")

print("\n" + "="*60)
print("CONCLUSION")
print("="*60)
if best_score > best_score_norm:
    print("✓ LES DONNÉES ORIGINALES DONNENT DE MEILLEURS RÉSULTATS")
    print(f"  Algorithme à retenir: {best_classifieur}")
    print(f"  Score: {best_score:.3f}")
    print("\n→ STRATÉGIE: Ne pas normaliser les données")
else:
    print("✓ LES DONNÉES NORMALISÉES DONNENT DE MEILLEURS RÉSULTATS")
    print(f"  Algorithme à retenir: {best_classifieur_norm}")
    print(f"  Score: {best_score_norm:.3f}")
    print("\n→ STRATÉGIE: Normaliser les données")


SYNTHÈSE DES RÉSULTATS
Meilleur sur données originales: Bagging
Score: 0.783

Meilleur sur données normalisées: MLP
Score: 0.809

CONCLUSION
✓ LES DONNÉES NORMALISÉES DONNENT DE MEILLEURS RÉSULTATS
  Algorithme à retenir: MLP
  Score: 0.809

→ STRATÉGIE: Normaliser les données
